version: "3"
services:
  clickhouse:
    image: "clickhouse/clickhouse-server:24.3-alpine"
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ''
